baseURL = "https://pcluster.cloud"
languageCode = 'en-us'
title = 'ParallelCluster UI Docs'
theme = "hugo-theme-learn"
uglyurls = true
sectionPagesMenu = "main"
pygmentsCodeFences = true

[blackfriday]
hrefTargetBlank = true

[params]
editURL = "https://github.com/sean-smith/pcluster.cloud/tree/main/content/"
themeVariant = "mine"
showVisitedLinks = true
description = "ParallelCluster UI Docs"
disableSearch = false
disableAssetsBusting = false
disableLanguageSwitchingButton = true
disableShortcutsTitle = false
disableLandingPageButton = true

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Github"
url = "https://github.com/sean-smith/pcluster.cloud"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> AWS - HPC"
url = "https://aws.amazon.com/hpc/"
weight = 10
